In [10]:
import numpy as np
neuron = 4

In [11]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

In [12]:
def sigmoid_derivative(x):
    return x * (1.0 - x)

In [13]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        print('inputs \n' , self.input)
        print()
        self.weights1 = np.random.rand(self.input.shape[1],neuron)
        print('weights1 \n',self.weights1)
        print()
        self.weights2 = np.random.rand(neuron,1)
        print('weights2 \n',self.weights2)
        print()
        self.y = y                           # y original
        print('y \n',self.y)
        print()
        self.output = np.zeros(self.y.shape) # y hat
        print('output \n',self.output)
        print()
        
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        #print('layer 1 \n',self.layer1)
        #print()
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        #print('output \n',self.output)
        #print()
    
    
    
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        #print('d_weights2 \n',d_weights2 )
        #print()
        d_weights1 = np.dot(self.input.T,
                (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output),
                        self.weights2.T) * sigmoid_derivative(self.layer1)))
        # print('d_weights1 \n',d_weights1)
        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

In [14]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

In [22]:
nn = NeuralNetwork(X,y)

for i in range(50000):
    nn.feedforward()
    nn.backprop()
    #print('--------result-----------')
    #print(nn.output)
    #print('++++++++++++++++++++++++++++++++++++++++++')
print('NN output \n',nn.output)    

inputs 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights1 
 [[0.84421451 0.93194262 0.34833981 0.25670424]
 [0.48923417 0.95024494 0.0692262  0.1233968 ]
 [0.69946225 0.52922706 0.21483794 0.95450215]]

weights2 
 [[0.49612475]
 [0.53298315]
 [0.36280165]
 [0.48833471]]

y 
 [[0]
 [1]
 [1]
 [0]]

output 
 [[0.]
 [0.]
 [0.]
 [0.]]

NN output 
 [[0.00272432]
 [0.99698872]
 [0.99736393]
 [0.00297181]]
